name: Flutter CI

on:
    push:
        branches:
        - main
        - master
    pull_request:
        branches:
        - main
        - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

        # Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.24.0'

        # Install dependencies
      - name: Install dependencies
        run: flutter pub get

        # Run the tests
      - name: Run tests
        run: flutter test
